# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/here/pb/hdmap/shared/v1/core/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='com/here/pb/hdmap/shared/v1/core/common.proto',
  package='com.here.pb.hdmap.shared.v1.core',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-com/here/pb/hdmap/shared/v1/core/common.proto\x12 com.here.pb.hdmap.shared.v1.core\"\xe5\x01\n\tRoadUsers\x12\x13\n\x0b\x61utomobiles\x18\x01 \x01(\x08\x12\r\n\x05\x62uses\x18\x02 \x01(\x08\x12\r\n\x05taxis\x18\x03 \x01(\x08\x12\x10\n\x08\x63\x61rpools\x18\x04 \x01(\x08\x12\x13\n\x0bpedestrians\x18\x05 \x01(\x08\x12\x0e\n\x06trucks\x18\x06 \x01(\x08\x12\x17\n\x0fthrough_traffic\x18\x07 \x01(\x08\x12\x12\n\ndeliveries\x18\x08 \x01(\x08\x12\x1a\n\x12\x65mergency_vehicles\x18\t \x01(\x08\x12\x13\n\x0bmotorcycles\x18\n \x01(\x08\x12\x10\n\x08\x62icycles\x18\x0b \x01(\x08\"\xae\x04\n\nSpeedLimit\x12\r\n\x05value\x18\x01 \x01(\r\x12I\n\x04unit\x18\x02 \x01(\x0e\x32;.com.here.pb.hdmap.shared.v1.core.SpeedLimit.SpeedLimitUnit\x12M\n\x06source\x18\x03 \x01(\x0e\x32=.com.here.pb.hdmap.shared.v1.core.SpeedLimit.SpeedLimitSource\x12\x14\n\x0cis_unlimited\x18\x04 \x01(\x08\"[\n\x0eSpeedLimitUnit\x12\x1c\n\x18SPEED_LIMIT_UNIT_UNKNOWN\x10\x00\x12\x17\n\x13KILOMETERS_PER_HOUR\x10\x01\x12\x12\n\x0eMILES_PER_HOUR\x10\x02\"\x83\x02\n\x10SpeedLimitSource\x12\x1e\n\x1aSPEED_LIMIT_SOURCE_UNKNOWN\x10\x00\x12\x0f\n\x0bPOSTED_SIGN\x10\x01\x12\x16\n\x12\x42UILT_UP_AREA_SIGN\x10\x02\x12\x11\n\rMOTORWAY_SIGN\x10\x03\x12\x0c\n\x08UNPOSTED\x10\x04\x12\x0f\n\x0bPOSTED_LANE\x10\x05\x12\x0e\n\nPOSTED_DIR\x10\x06\x12\x1b\n\x17MOTORISED_VEHICLES_ONLY\x10\x07\x12\x1f\n\x1b\x44\x45RIVED_FROM_SPEED_CATEGORY\x10\x08\x12\x11\n\rRAMP_UNPOSTED\x10\t\x12\x13\n\x0fTRAFFIC_CALMING\x10\nb\x06proto3'
)



_SPEEDLIMIT_SPEEDLIMITUNIT = _descriptor.EnumDescriptor(
  name='SpeedLimitUnit',
  full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.SpeedLimitUnit',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPEED_LIMIT_UNIT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KILOMETERS_PER_HOUR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MILES_PER_HOUR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=521,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_SPEEDLIMIT_SPEEDLIMITUNIT)

_SPEEDLIMIT_SPEEDLIMITSOURCE = _descriptor.EnumDescriptor(
  name='SpeedLimitSource',
  full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.SpeedLimitSource',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPEED_LIMIT_SOURCE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POSTED_SIGN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUILT_UP_AREA_SIGN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTORWAY_SIGN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNPOSTED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POSTED_LANE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POSTED_DIR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTORISED_VEHICLES_ONLY', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DERIVED_FROM_SPEED_CATEGORY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAMP_UNPOSTED', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRAFFIC_CALMING', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=615,
  serialized_end=874,
)
_sym_db.RegisterEnumDescriptor(_SPEEDLIMIT_SPEEDLIMITSOURCE)


_ROADUSERS = _descriptor.Descriptor(
  name='RoadUsers',
  full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='automobiles', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.automobiles', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buses', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.buses', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taxis', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.taxis', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='carpools', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.carpools', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pedestrians', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.pedestrians', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trucks', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.trucks', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='through_traffic', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.through_traffic', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deliveries', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.deliveries', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emergency_vehicles', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.emergency_vehicles', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motorcycles', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.motorcycles', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bicycles', full_name='com.here.pb.hdmap.shared.v1.core.RoadUsers.bicycles', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=313,
)


_SPEEDLIMIT = _descriptor.Descriptor(
  name='SpeedLimit',
  full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.unit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.source', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_unlimited', full_name='com.here.pb.hdmap.shared.v1.core.SpeedLimit.is_unlimited', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPEEDLIMIT_SPEEDLIMITUNIT,
    _SPEEDLIMIT_SPEEDLIMITSOURCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=874,
)

_SPEEDLIMIT.fields_by_name['unit'].enum_type = _SPEEDLIMIT_SPEEDLIMITUNIT
_SPEEDLIMIT.fields_by_name['source'].enum_type = _SPEEDLIMIT_SPEEDLIMITSOURCE
_SPEEDLIMIT_SPEEDLIMITUNIT.containing_type = _SPEEDLIMIT
_SPEEDLIMIT_SPEEDLIMITSOURCE.containing_type = _SPEEDLIMIT
DESCRIPTOR.message_types_by_name['RoadUsers'] = _ROADUSERS
DESCRIPTOR.message_types_by_name['SpeedLimit'] = _SPEEDLIMIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoadUsers = _reflection.GeneratedProtocolMessageType('RoadUsers', (_message.Message,), {
  'DESCRIPTOR' : _ROADUSERS,
  '__module__' : 'com.here.pb.hdmap.shared.v1.core.common_pb2'
  # @@protoc_insertion_point(class_scope:com.here.pb.hdmap.shared.v1.core.RoadUsers)
  })
_sym_db.RegisterMessage(RoadUsers)

SpeedLimit = _reflection.GeneratedProtocolMessageType('SpeedLimit', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDLIMIT,
  '__module__' : 'com.here.pb.hdmap.shared.v1.core.common_pb2'
  # @@protoc_insertion_point(class_scope:com.here.pb.hdmap.shared.v1.core.SpeedLimit)
  })
_sym_db.RegisterMessage(SpeedLimit)


# @@protoc_insertion_point(module_scope)
